trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '**/*task.json'
    - '**/vss-extension.json'
    
pool:
  vmImage: 'windows-latest'

variables:
- group: run-stryker-task

resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/heads/master
      name: pipeline-templates

extends:
  template: Deploy\azure-devops-marketplace.yml@templates